@FlightReservation.API_HostAddress = http://localhost:5248

GET {{FlightReservation.API_HostAddress}}/weatherforecast/
Accept: application/json

###



POST {{FlightReservation.API_HostAddress}}/auth/register
Accept: application/json
{
  "email": "string",
  "password": "string",
  "firstName": "string",
  "lastName": "string",
  "userName": "string"
}
